create warehouse wh11
warehouse_size='XSMALL'
auto_suspend=60
auto_resume=true
initially_suspended=true;
use warehouse wh11;


CREATE OR REPLACE DATABASE CUSTOMER_MDM_DB;

CREATE OR REPLACE SCHEMA CUSTOMER_MDM_DB.CUSTOMER_SCHEMA;

USE DATABASE CUSTOMER_MDM_DB;
USE SCHEMA CUSTOMER_SCHEMA;

CREATE OR REPLACE TABLE CUSTOMER_DIM (
    CUSTOMER_KEY NUMBER AUTOINCREMENT,
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR(100),
    CITY VARCHAR(50),
    PREVIOUS_CITY VARCHAR(50),
    STATE VARCHAR(50),
    CURRENT_MEMBERSHIP VARCHAR(30),
    PREVIOUS_MEMBERSHIP VARCHAR(30),
    HISTORICAL_MEMBERSHIP VARCHAR(30),
    SEGMENT VARCHAR(30),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    IS_CURRENT BOOLEAN
);
-- Insert New Active Versions
INSERT INTO CUSTOMER_DIM
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
VALUES
(101, 'Amit Sharma', 'Hyderabad', NULL, 'Telangana',
 'Silver', NULL, 'Silver', 'Regular',
 '2026-01-01', '9999-12-31', TRUE),

(102, 'Priya Reddy', 'Warangal', NULL, 'Telangana',
 'Gold', NULL, 'Gold', 'Premium',
 '2026-01-01', '9999-12-31', TRUE),

(103, 'Rahul Verma', 'Vijayawada', NULL, 'Andhra Pradesh',
 'Silver', NULL, 'Silver', 'Regular',
 '2026-01-01', '9999-12-31', TRUE),

(104, 'Neha Patel', 'Hyderabad', NULL, 'Telangana',
 'Gold', NULL, 'Gold', 'Premium',
 '2026-01-01', '9999-12-31', TRUE),

(105, 'Arjun Gupta', 'Nagpur', NULL, 'Maharashtra',
 'Bronze', NULL, 'Bronze', 'Regular',
 '2026-01-01', '9999-12-31', TRUE);


-- Synchronize Global Current Membership
 SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM CUSTOMER_DIM
ORDER BY CUSTOMER_ID;

UPDATE CUSTOMER_DIM
SET
    EXPIRY_DATE = DATEADD(DAY, -1, U.EFFECTIVE_DATE),
    IS_CURRENT = FALSE
FROM (
    SELECT 101 AS CUSTOMER_ID, '2026-04-01'::DATE AS EFFECTIVE_DATE
    UNION ALL
    SELECT 103, '2026-04-05'::DATE
    UNION ALL
    SELECT 104, '2026-04-10'::DATE
) U
WHERE CUSTOMER_DIM.CUSTOMER_ID = U.CUSTOMER_ID
AND CUSTOMER_DIM.IS_CURRENT = TRUE;


-- Synchronize Previous Membership
INSERT INTO CUSTOMER_DIM
(
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
)
SELECT
    101,
    'Amit Sharma',
    'Bengaluru',
    'Hyderabad',
    'Karnataka',
    'Gold',
    'Silver',
    'Gold',
    'Premium',
    '2026-04-01',
    '9999-12-31',
    TRUE

UNION ALL

SELECT
    103,
    'Rahul Verma',
    'Chennai',
    'Vijayawada',
    'Tamil Nadu',
    'Gold',
    'Silver',
    'Gold',
    'Premium',
    '2026-04-05',
    '9999-12-31',
    TRUE

UNION ALL

SELECT
    104,
    'Neha Patel',
    'Hyderabad',
    NULL,
    'Telangana',
    'Platinum',
    'Gold',
    'Platinum',
    'Premium',
    '2026-04-10',
    '9999-12-31',
    TRUE;

    UPDATE CUSTOMER_DIM D
SET CURRENT_MEMBERSHIP = X.CURRENT_MEMBERSHIP
FROM (
    SELECT
        CUSTOMER_ID,
        CURRENT_MEMBERSHIP
    FROM CUSTOMER_DIM
    WHERE IS_CURRENT = TRUE
) X
WHERE D.CUSTOMER_ID = X.CUSTOMER_ID;

-- Synchronize Current City
UPDATE CUSTOMER_DIM D
SET PREVIOUS_MEMBERSHIP = X.PREVIOUS_MEMBERSHIP
FROM (
    SELECT
        CUSTOMER_ID,
        PREVIOUS_MEMBERSHIP
    FROM CUSTOMER_DIM
    WHERE IS_CURRENT = TRUE
) X
WHERE D.CUSTOMER_ID = X.CUSTOMER_ID;

UPDATE CUSTOMER_DIM D
SET
    CITY = X.CITY,
    PREVIOUS_CITY = X.PREVIOUS_CITY,
    STATE = X.STATE
FROM (
    SELECT
        CUSTOMER_ID,
        CITY,
        PREVIOUS_CITY,
        STATE
    FROM CUSTOMER_DIM
    WHERE IS_CURRENT = TRUE
) X
WHERE D.CUSTOMER_ID = X.CUSTOMER_ID;

-- Display Complete Dimension History
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE,
    IS_CURRENT
FROM CUSTOMER_DIM
ORDER BY CUSTOMER_ID, EFFECTIVE_DATE;

-- Active Customer Report
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    PREVIOUS_CITY,
    STATE,
    CURRENT_MEMBERSHIP,
    PREVIOUS_MEMBERSHIP,
    SEGMENT
FROM CUSTOMER_DIM
WHERE IS_CURRENT = TRUE
ORDER BY CUSTOMER_ID;



-- Point-in-Time Historical Query
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    HISTORICAL_MEMBERSHIP,
    SEGMENT,
    EFFECTIVE_DATE,
    EXPIRY_DATE
FROM CUSTOMER_DIM
WHERE CUSTOMER_ID = 101
AND '2026-03-15'::DATE BETWEEN EFFECTIVE_DATE AND EXPIRY_DATE;


-- Metric Validation
SELECT
    COUNT(*) AS TOTAL_RECORD_COUNT,
    COUNT_IF(IS_CURRENT = TRUE) AS CURRENT_RECORD_COUNT,
    COUNT_IF(IS_CURRENT = FALSE) AS HISTORICAL_RECORD_COUNT
FROM CUSTOMER_DIM;
